name: pestworks
favicon: null
layout_spectrum: 0.97412
typography_spectrum: 0.0623
title: 'Pest Works - Software that Works for the Pest Control Industry, Finally'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#363636'
    - '#209346'
    - '#c0c0c0'
    - '#8e8e8e'
  brandStrength: 0.625
  lightness: 0.75
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
