name: null
favicon: null
layout_spectrum: 0.7347689773887396
typography_spectrum: 0.8971602469682693
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.20626517641358078
  lightness: 0.2756925425492227
  saturation: 0.24834029166959226
  rhythmicContrast: 0.8654028370510787
purpose: []
